services:
  - type: web
    name: emergency-module
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: YOUR_SID
      - key: TWILIO_AUTH_TOKEN
        value: YOUR_TOKEN
      - key: TWILIO_PHONE_NUMBER
        value: +1XXXXXXXXXX
